### PR TITLE
Added Enough Requirements and Purge mod

### PR DESCRIPTION
**Pull request by sppidy**

### CODE REVIEW

**Comment by iiiiii1wepfj** [comment]
why you added requests package to the requirements.txt file?

**Comment by sppidy** [comment]
> why you added requests package to the requirements.txt file?

it was need by dogbin by anonymous machine

**Comment by alissonlauffer** [comment]
It looks nice, but please remove the requests requirement from requirements.text. I'll update the module that were using it to HTTPX, which is better because it is async.

**Comment by iiiiii1wepfj** [comment]
shit, @sppidy can you make the the pr again?

**Comment by iiiiii1wepfj** [comment]
can i merge the pr?

**Pull request merged**
