### PR TITLE
Eduu code reorganized for package format

### PR DESCRIPTION
**Pull request by HitaloSama**
I did this reorganization using Black and Isort and at Alisson's request, I did not test exactly everything but it seems to me to be all working ~~, all GitHub workflows will fail because the location of the `version.txt` has been changed then Alisson should change the workflow configuration file~~.

### CODE REVIEW

**Review by iiiiii1wepfj — COMMENTED** [review]
but why?

**Review by iiiiii1wepfj — CHANGES_REQUESTED** [review]
the code not workimg

**Comment by AndrielFR** [comment]
> but why?

But why no?

**Comment by alissonlauffer** [comment]
Overall it looks good, but for eduu.database I would move it into a database.py file, since there is just one file.

**Comment by HitaloSama** [comment]
> Overall it looks good, but for eduu.database I would move it into a database.py file, since there is just one file.

I left it in a folder because it creates the `eduu.db` so I thought it would be better.

**Review by iiiiii1wepfj — APPROVED** [review]
good

**Review by alissonlauffer — APPROVED** [review]

**Pull request merged**
