### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by alissonlauffer**

### CODE REVIEW

**Review by HitaloSama — CHANGES_REQUESTED** [review]
The hell is this Alisson???

**Comment by alissonlauffer** [comment]
> The hell is this Alisson???

@HitaloSama some translations were done, but I reverted them, so the "Files changed" counter went to 0. I left it open so this PR can be reutilized.

**Comment by HitaloSama** [comment]
@alissonlauffer Faz sentido CEO

**Comment by HitaloSama** [comment]
> > The hell is this Alisson???
> 
> @HitaloSama some translations were done, but I reverted them, so the "Files changed" counter went to 0. I left it open so this PR can be reutilized.

Faz sentido CEO

**Comment by alissonlauffer** [comment]
Turkish translation has been revised a bit now. Also added a missing dot in Brazilian Portuguese translation.

**Review by HitaloSama — APPROVED** [review]
I don't understand Turkish, but it should be fine.

**Review by AndrielFR — APPROVED** [review]

**Pull request merged**
