### PR TITLE
Better code

### PR DESCRIPTION
**Pull request by rojserbest**

### CODE REVIEW

**Comment by iiiiii1wepfj** [comment]
send the pr without replace the c

**Comment by alissonlauffer** [comment]
About the change from `c: Client` to `_`:
 - I don't like it since the variable may be used at some point.

**Comment by rojserbest** [comment]
OK, but can you please reopen?

**Comment by alissonlauffer** [comment]
Doesn't that code breaks rules in normal groups?

**Comment by rojserbest** [comment]
You know what, I didn't modify Itay's way so that is a question to be asked to Itay.

**Comment by alissonlauffer** [comment]
@iiiiii1wepfj can you stop merging pull requests without my approval? Thanks.

**Comment by HitaloSama** [comment]
@alissonlauffer HAHAHAHAHAHA

**Comment by iiiiii1wepfj** [comment]
> @iiiiii1wepfj can you stop merging pull requests without my approval? Thanks.

ok

**Comment by rojserbest** [comment]
> Doesn't that code break rules in normal groups?

You could have said groups that are not supergroups and sorry for my misunderstanding.

**Comment by rojserbest** [comment]
@iiiiii1wepfj you can replace '-100' with '-' in [here](https://github.com/AmanoTeam/EduuRobot/blob/10601476d118caf31487db7d1b38541da0e52e51/plugins/rules.py#L64).

**Pull request merged**
