### PR TITLE
update the languages list

### PR DESCRIPTION
**Pull request by iiiiii1wepfj**

### CODE REVIEW

**Comment by alissonlauffer** [comment]
Can you sort the languages alphabetically? Will be easier to find them.

**Comment by alissonlauffer** [comment]
By the way, storing the link inside a variable in the code is better, so if we need to change the url, it will not make translators to retranslate that string.

**Comment by iiiiii1wepfj** [comment]
> By the way, storing the link inside a variable in the code is better, so if we need to change the url, it will not make translators to retranslate that string.


i can try to do it later, but now i do it directly from the api

```
from pytio import Tio
tio = Tio()
langslist = tio.query_languages()
langsformat = ""
for i in langslist:
 langsformat += f"{i}\n"
with open ("langs.txt", "w") as langsfile:
 langsfile.write(langsformat)
```

**Comment by iiiiii1wepfj** [comment]
wait

**Comment by alissonlauffer** [comment]
> > By the way, storing the link inside a variable in the code is better, so if we need to change the url, it will not make translators to retranslate that string.
> 
> i can try to do it later, but now i do it directly from the api
> 
> ```
> from pytio import Tio
> tio = Tio()
> langslist = tio.query_languages()
> langsformat = ""
> for i in langslist:
>  langsformat += f"{i}\n"
> with open ("langs.txt", "w") as langsfile:
>  langsfile.write(langsformat)
> ```

```python
from pytio import Tio
tio = Tio()
langslist = sorted(tio.query_languages())

with open ("langs.txt", "w") as langsfile:
 langsfile.write("\n".join(langslist))
```

**Comment by iiiiii1wepfj** [comment]
done

**Comment by iiiiii1wepfj** [comment]
wait

**Comment by iiiiii1wepfj** [comment]
done

**Review by alissonlauffer — APPROVED** [review]

**Pull request merged**
