### PR TITLE
tortoise-orm

### PR DESCRIPTION
**Pull request by iiiiii1wepfj**

### CODE REVIEW

**Review by AndrielFR — CHANGES_REQUESTED** [review]
On the main branch, no, you can give up.

**Comment by alissonlauffer** [comment]
Well, as I am the "owner" of this project I will tell my opinion about using an ORM on it.

I particularly dislike ORMs, since they are often a "bloat" and can slow down queries and bulk processing, since they act as an intermediary between your code, the SQL queries and the database.

The EduuRobot project is often seen as an ideal project for new developers learning to code (this has been the case many times, even I learned to code with it). It follows security practices to not create SQL Injection (SQLI) vulnerabilities with raw SQL, which are very often committed and the main reason for data breaches. This can benefit new developers to not make these mistakes while making SQL queries and then make the internet a safer place.

I also like simplicity and to use the stdlib of the language as much as possible, not having hundreds of dependencies like a Node.js project.

To make everyone happy, I thought of an idea: Keep the main branch with SQLite, changing the default `sqlite3` module to `aiosqlite` (I'll do this in #289), and keep a secondary branch (named main-form) with the same bot base, but using Tortoise ORM.

Also, a note in README will be added, explaining this and recommending the ORM branch + another database for Heroku.

**Comment by alissonlauffer** [comment]
By the way, this PR will be on hold and will be rebased after #289 is done and merged.

**Comment by iiiiii1wepfj** [comment]
> By the way, this PR will be on hold and will be rebased after #289 is done and merged (since I will be making significant changes to database).

but i want orm

**Pull request closed without merging**
