### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by alissonlauffer**

### CODE REVIEW

**Review by AndrielFR — APPROVED** [review]
I didn't understand anything, but I think it's right.

**Review by iiiiii1wepfj — APPROVED** [review]

**Comment by iiiiii1wepfj** [comment]
> I didn't understand anything, but I think it's right.

same (but i am learning this language)

**Comment by AndrielFR** [comment]
> > I didn't understand anything, but I think it's right.
> 
> same (but i am learning this language)

Oh, cool.

**Review by HitaloSama — APPROVED** [review]
I don't understand anything either, but I think it's all right.

**Comment by alissonlauffer** [comment]
Ok, I'll wait until more strings are translated and then merge.

**Comment by iiiiii1wepfj** [comment]
> I don't understand anything either, but I think it's all right.

۲۰۲۱.٥.۱۸

**Comment by iiiiii1wepfj** [comment]
> > I don't understand anything either, but I think it's all right.
> 
> ۲۰۲۱.٥.۱۸

this is the date in arabic

**Pull request merged**
